########################################################
# This creates a repository resource named ALMTemplates
# and points to the ALM devops_pipeline repository.
########################################################
resources:
  repositories:                                                                        
    - repository: 'AlmTemplates'
      type: git
      name: ALM/devops_pipelines
      #ref: develop                                                                     # Please uncomment this line if you need to run on our dev template. 
 
trigger:
- none                                                                                  # Change this value to a branch name if a CI build is desired. For more information on triggers: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers
 
####################################################################################################
# Name the stage what ever you like.
# For more information on stages:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml
####################################################################################################
stages:
  - stage: 'Build Stage'                                                               
    jobs:
      - job:
        displayName: Build                                                              # Again name the job what ever you want. For more information on jobs: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=azure-devops
        pool:
          name: Default                                                                 # Change the pool name to which ever pool is needed. Use 'Default' for Windows agents 'Private Linux' for Linux agents.
        steps:                                                                          # for more information on steps: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#steps
        - template: '.netcore-build/.netcore-build.yml@AlmTemplates'                         # This line calls the ALM .Net Core template task. If any default parameters need to be changed, uncomment the parameter section and the parameter that needs to be changed.
         #parameters:                                                                   # Parameters need not be added if the defaults meet your needs. Uncomment the below section and parameter line to change the defaults if needed.  
            #DotNetVersion: '3.x'                                                       # Set the dotnet version needed to build your project. Default is 3.X
            #BuildConfiguration: 'release'                                              # Enter the Build configuration needed. Default Debug.
            #DownloadSecureFile: false                                                  # Set to true if a secure file is needed. Default false.
            #RunArtifactoryUpload: true                                                 # Set to false to disable artifactory upload. Default true. 
            #TestPath: "**/*Tests/*.csproj"                                             # Enter test project path. Default is **/*tests/*.csproj
            #RunTests: true                                                             # Set to true if tests runs desired. Default false.
            #ZipAfterPublish: false                                                     # Set to false if zip not required after the dotnet publish step. Default true.
            #SonarScan: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/master') }} # This expression will return true if the branch is master. Set to 'false' if a scan is unwanted on the master branch. Default false.
            #SonarProjectKey: 'Awesome App'                                             # Enter the app name for a Sonar Scan. Don't use if Sonar Scan set to false. No Default.
            #SonarServiceConnection: 'sonar test'                                       # Service connection for Sonar Scan. Don't use if Sonar Scan set to false. Default 'ALM Sonar'
            #ProjectPaths: 'pipelines-dotnet-core.sln'                                  # Enter solution path or project path. Default is **/*.sln
            #AdditionalBuildArgs:                                                       # Enter any additional dotnet build arguments if needed.
            #AdditionalPublishArgs:                                                     # Enter any additional dotnet publish arguments if needed.
 
#################################################################################################
# Add any other tasks needed for your pipeline. The below task is an example and can be removed.
# After the step template above, any other tasks can be run.
#################################################################################################
        - script: 'Echo hello world'