# EP - Test pipeline to run job templates
# This example pipeline calls the template from the templates directory in the same repo or in devops_pipelines
# To call the template from a different repo use the resources block
###########################################################################################################################
# Lines that should be caught 24, 30, 49, 88, 126, 146, 167, 217, 237, 274, 294, 341, 361, 383
###########################################################################################################################
trigger:
- none

resources:
  repositories:
    - repository: CodeRepository
      type: git
      name: ALM/java-template-testing
      ref: 'master' # The code branch should always be master

stages:
# ************************************
# ***** Stage Maven_Build *****
# ************************************

- stage: cf_push_deploy_1
  jobs:
  - template: ../cloudfoundry-deploy/cf-deploy-job.yml
    parameters:
  condition: always()

- stage: Artifactory_Java_Build_alm_agent_8
  jobs:
  - template: templates/azure-java-mvn-docker.yml@almtemplates
    parameters:
      # AppName: 'Docker-Mikes'
      JavaVersion: '11' # Values can be 11 or 8. Default maven version is 11
      ArtifactoryServiceConnection: 'Mikes' # Required. Not on all projects yet. Artifactory service connection
      SonarServiceConnection: 'SonarServiceConnection'
      ArtifactoryExtDockerRegistry: 'DockerServiceConnection'
      RunMavenSonarScan: 'true'
      MavenGoal: 'clean deploy' # Optional
      targetResolveReleaseRepo: 'mvn' # Optional
      targetResolveSnapshotRepo: 'mvn'# Optional
      targetDeployReleaseRepo: 'mvn-local-ics-releases'# Optional
      targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'# Optional
      AppVersion: '1.0'
      agent: 'alm agent 8'
  condition: always()

- stage: MarkLogic_Build
  jobs:
  - template: ../marklogic/marklogic-build.yml
    parameters:
      AgentDemands: 'Docker'
      checkout: CodeRepository
      ContentsVars: 
        Variable1: "**/*.jar"
        Variable2: "**/manifest*.yml"
        Variable3: "**/pom.xml"
        Variable4: "**/*.xar"
      JavaVersion: '11' # Values can be 11 or 8. Default maven version is 11
      MavenGoal: '--batch-mode clean install -e -U' # Optional
      MavenPomFile: 'pom.xml'
      # MavenPomPath: '.' # Location of Maven pom file
      XarProfile: '${{ variables.profile }}'

- stage: MarkLogic_Deploy
  jobs:
  - template: ../marklogic/marklogic-deploy.yml
    parameters:
      ArtifactPath: '${{ variables.artifactPath }}'
      BuildType: 'current'
      checkout: CodeRepository
      XarFilePath: '${{ variables.targetPath }}/${{ variables.XarArtifactPath }}/${{ variables.ZipFilePattern }}'
      test: '${{ variables.targetPath }}/${{ variables.XarArtifactPath }}/'
      JavaVersion: '11' # Values can be 11 or 8. Default maven version is 11
      MavenGoal: '--batch-mode xar:deploy' # Optional
      MavenPomFile: 'pom.xml'
      MavenPomPath: '.' # Location of Maven pom file
      Pipeline: '$(Build.DefinitionName)' # https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
      Project: '$(System.TeamProject)'    # https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
      SpecificBuildWithTriggering: true
      TargetPath: '${{ variables.TargetPath }}'
      XarArtifactPath: '${{ variables.XarArtifactPath }}'
      XarFileName: '${{ variables.XarFileName }}'
      DeployCommand: 'xcc://deployment:deployment@l12870.ldschurch.org:8010'
      #Profile: '${{ variables.profile }}'

- stage: Artifactory_Java_Build_alm_agent_9
  jobs:
  - template: templates/azure-java-mvn-docker.yml@almtemplates
    parameters:
      AppName: 'Docker-Mikes'
      Portfolio: 'ESM'
      JavaVersion: '11' # Values can be 11 or 8. Default maven version is 11
      ArtifactoryServiceConnection: 'Mikes' # Required. Not on all projects yet. Artifactory service connection
      SonarServiceConnection: 'SonarServiceConnection'
      ArtifactoryExtDockerRegistry: 'DockerServiceConnection'
      RunMavenSonarScan: 'true'
      MavenGoal: 'clean deploy' # Optional
      targetResolveReleaseRepo: 'mvn' # Optional
      targetResolveSnapshotRepo: 'mvn'# Optional
      targetDeployReleaseRepo: 'mvn-local-ics-releases'# Optional
      targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'# Optional
      AppVersion: '1.0'
      agent: 'alm agent 9'
  condition: always()

# - stage: Artifactory_Java_Build_l15890_1
#   jobs:
#  - template: templates/azure-java-mvn-docker.yml@almtemplates
#     parameters:
#       AppName: 'Java-Mikes'
#       Portfolio: 'ESM'
#       JavaVersion: '11' # Values can be 11 or 8. Default maven version is 11
#       ArtifactoryServiceConnection: 'Mikes' # Required. Not on all projects yet. Artifactory service connection
#       SonarServiceConnection: 'SonarServiceConnection'
#       RunMavenSonarScan: 'false'
#       MavenGoal: 'clean deploy -DskipTests=true' # Optional
#       targetResolveReleaseRepo: 'mvn' # Optional
#       targetResolveSnapshotRepo: 'mvn'# Optional
#       targetDeployReleaseRepo: 'mvn-local-ics-releases'# Optional
#       targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'# Optional
#       agent: 'l15890-1'
#   condition: always()

- stage: Artifactory_Java_Build_l15890_2
  jobs:
  - template: templates/azure-java-mvn-docker.yml@almtemplates
    parameters:
      AppName: 'Docker-Mikes'
      Portfolio: 'ESM'
      JavaVersion: '11' # Values can be 11 or 8. Default maven version is 11
      ArtifactoryServiceConnection: 'Mikes' # Required. Not on all projects yet. Artifactory service connection
      SonarServiceConnection: 'SonarServiceConnection'
      ArtifactoryExtDockerRegistry: 'DockerServiceConnection'
      RunMavenSonarScan: 'true'
      MavenGoal: 'clean deploy' # Optional
      targetResolveReleaseRepo: 'mvn' # Optional
      targetResolveSnapshotRepo: 'mvn'# Optional
      targetDeployReleaseRepo: 'mvn-local-ics-releases'# Optional
      targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'# Optional
      AppVersion: '1.0'
      agent: 'l15890-2'
  condition: always()

- stage: jsstack_one
  jobs:
  - template: ../jsstack-pipeline/jsstack-pipeline.yml
    parameters:
      Portfolio: 'ESM'
      AppName: 'jsstack-Mikes'
      # ArtifactoryServiceConnection: 'ALM Artifactory Internal'
      # ArtifactoryExtDockerRegistry: 'ALM Docker'
      # Dockerfile: '**/Dockerfile'
      checkout: CodeRepository
  condition: always()

# - stage: jsstack_one
#   jobs:
#   - template: ../jsstack-pipeline/jsstack-pipeline.yml
#     parameters:
#       Portfolio: 'ESM'
#       AppName: 'jsstack-Mikes'
#       checkout: CodeRepository
#   condition: always()

- stage: Artifactory_Java_Build_l15890_3
  jobs:
  - template: templates/azure-java-mvn-docker.yml@almtemplates
    parameters:
      AppName: 'Docker-Mikes'
      Portfolio: 'ESM'
      JavaVersion: '11' # Values can be 11 or 8. Default maven version is 11
      ArtifactoryServiceConnection: 'Mikes' # Required. Not on all projects yet. Artifactory service connection
      SonarServiceConnection: 'SonarServiceConnection'
      ArtifactoryExtDockerRegistry: 'DockerServiceConnection'
      RunMavenSonarScan: 'true'
      MavenGoal: 'clean deploy' # Optional
      targetResolveReleaseRepo: 'mvn' # Optional
      targetResolveSnapshotRepo: 'mvn'# Optional
      targetDeployReleaseRepo: 'mvn-local-ics-releases'# Optional
      targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'# Optional
      AppVersion: '1.0'
      agent: 'l15890-3'
  condition: always()

- stage: javascript_npm_build
  jobs:
  - template: ../javascript-npm-build/javascript-npm-build.yml
    parameters:
      AppName: 'Mikes-ALM'
      Portfolio: 'ESM'
      RunMavenSonarScan: 'true'
      ArtifactoryServiceConnection: 'ALM Artifactory Internal'
      ArtifactoryExtDockerRegistry: 'ALM Docker'
      SonarServiceConnection: 'ALM Sonar'
      NodeVersion: '12.16.3'
      continueOnError: false  # 'true' if future steps should run even if this step fails; defaults to 'false'
      checkout: CodeRepository
  condition: always()

- stage: javascript_npm_build
  jobs:
  - template: ../javascript-npm-build/javascript-npm-build.yml
    parameters:
      AppName: 'Mikes-ALM'
      Portfolio: 'ESM'
      #RunMavenSonarScan: 'true'
      #ArtifactoryServiceConnection: 'ALM Artifactory Internal'
      #ArtifactoryExtDockerRegistry: 'ALM Docker'
      SonarServiceConnection: 'ALM Sonar'
      NodeVersion: '12.16.3'
      continueOnError: false  # 'true' if future steps should run even if this step fails; defaults to 'false'
      checkout: CodeRepository
  condition: always()

- stage: Artifactory_Java_Build_l17931_1
  jobs:
  - template: templates/azure-java-mvn-docker.yml@almtemplates
    parameters:
      AppName: 'Docker-Mikes'
      Portfolio: 'ESM'
      JavaVersion: '11' # Values can be 11 or 8. Default maven version is 11
      ArtifactoryServiceConnection: 'Mikes' # Required. Not on all projects yet. Artifactory service connection
      SonarServiceConnection: 'SonarServiceConnection'
      ArtifactoryExtDockerRegistry: 'DockerServiceConnection'
      RunMavenSonarScan: 'true'
      MavenGoal: 'clean deploy' # Optional
      targetResolveReleaseRepo: 'mvn' # Optional
      targetResolveSnapshotRepo: 'mvn'# Optional
      targetDeployReleaseRepo: 'mvn-local-ics-releases'# Optional
      targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'# Optional
      AppVersion: '1.0'
      agent: 'l17931-1'
  condition: always()

- stage: Artifactory_Java_Build_l17931_2
  jobs:
  - template: templates/azure-java-mvn-docker.yml@almtemplates
    parameters:
      AppName: 'Docker-Mikes'
      Portfolio: 'ESM'
      JavaVersion: '11' # Values can be 11 or 8. Default maven version is 11
      ArtifactoryServiceConnection: 'Mikes' # Required. Not on all projects yet. Artifactory service connection
      SonarServiceConnection: 'SonarServiceConnection'
      ArtifactoryExtDockerRegistry: 'DockerServiceConnection'
      RunMavenSonarScan: 'true'
      MavenGoal: 'clean deploy' # Optional
      targetResolveReleaseRepo: 'mvn' # Optional
      targetResolveSnapshotRepo: 'mvn'# Optional
      targetDeployReleaseRepo: 'mvn-local-ics-releases'# Optional
      targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'# Optional
      AppVersion: '1.0'
      agent: 'l17931-2'
  condition: always()

- stage: java_mvn_build_1
  jobs:
  - template: ../java-mvn-build/java-mvn-build.yml
    parameters:
      AppName: 'Java-Mikes'
      Portfolio: 'ESM'
      RunMavenSonarScan: 'true'
      MavenGoal: 'clean install' # Optional
      targetResolveReleaseRepo: 'mvn' # Optional
      targetResolveSnapshotRepo: 'mvn'# Optional
      targetDeployReleaseRepo: 'mvn-local-ics-releases'# Optional
      targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'# Optional
      continueOnError: false  # 'true' if future steps should run even if this step fails; defaults to 'false'
      jobName: 'Test'
      checkout: CodeRepository
  condition: always()

- stage: Artifactory_Java_Build_l17931_3
  jobs:
  - template: templates/azure-java-mvn-docker.yml@almtemplates
    parameters:
      AppName: 'Docker-Mikes'
      Portfolio: 'ESM'
      JavaVersion: '11' # Values can be 11 or 8. Default maven version is 11
      ArtifactoryServiceConnection: 'Mikes' # Required. Not on all projects yet. Artifactory service connection
      SonarServiceConnection: 'SonarServiceConnection'
      ArtifactoryExtDockerRegistry: 'DockerServiceConnection'
      RunMavenSonarScan: 'true'
      MavenGoal: 'clean deploy' # Optional
      targetResolveReleaseRepo: 'mvn' # Optional
      targetResolveSnapshotRepo: 'mvn'# Optional
      targetDeployReleaseRepo: 'mvn-local-ics-releases'# Optional
      targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'# Optional
      AppVersion: '1.0'
      agent: 'l17931-3'
  condition: always()

- stage: Artifactory_Java_Build_l17931_4
  jobs:
  - template: templates/azure-java-mvn-docker.yml@almtemplates
    parameters:
      AppName: 'Docker-Mikes'
      Portfolio: 'ESM'
      JavaVersion: '11' # Values can be 11 or 8. Default maven version is 11
      ArtifactoryServiceConnection: 'Mikes' # Required. Not on all projects yet. Artifactory service connection
      SonarServiceConnection: 'SonarServiceConnection'
      ArtifactoryExtDockerRegistry: 'DockerServiceConnection'
      RunMavenSonarScan: 'true'
      MavenGoal: 'clean deploy' # Optional
      targetResolveReleaseRepo: 'mvn' # Optional
      targetResolveSnapshotRepo: 'mvn'# Optional
      targetDeployReleaseRepo: 'mvn-local-ics-releases'# Optional
      targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'# Optional
      AppVersion: '1.0'
      agent: 'l17931-4'
  condition: always()

- stage: 'Dot_Net_Core_Build_1'
  jobs:
  - job: 
    displayName: dotnetCore_build_1 
    condition: always()
    pool:
        name: Default
    steps:
    - checkout: 'dotnetCode' # Prevent code check out
      clean: true

    - template: ../.netcore-build/.netcore-build.yml
      parameters:
        DotNetVersion: '3.x'
        BuildConfiguration: release
        DownloadSecureFile: 'false'
        RunArtifactoryUpload: 'true'
        ProjectPaths: 'pipelines-dotnet-core.sln'
        TestPaths: 'tests\*.csproj'
        RunTests: true
        PublishWebProjects: true
        ZipAfterPublish: false
        SonarScan: true
        ArtifactoryServiceConnection: 'ALM Artifactory Internal'
        SonarServiceConnection: 'ALM Sonar'
        SonarProjectKey: 'DR-dotnetcore-test-2'

- stage: Artifactory_Java_Build_l17931_5
  jobs:
  - template: templates/azure-java-mvn-docker.yml@almtemplates
    parameters:
      AppName: 'Docker-Mikes'
      Portfolio: 'ESM'
      JavaVersion: '11' # Values can be 11 or 8. Default maven version is 11
      ArtifactoryServiceConnection: 'Mikes' # Required. Not on all projects yet. Artifactory service connection
      SonarServiceConnection: 'SonarServiceConnection'
      ArtifactoryExtDockerRegistry: 'DockerServiceConnection'
      RunMavenSonarScan: 'true'
      MavenGoal: 'clean deploy' # Optional
      targetResolveReleaseRepo: 'mvn' # Optional
      targetResolveSnapshotRepo: 'mvn'# Optional
      targetDeployReleaseRepo: 'mvn-local-ics-releases'# Optional
      targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'# Optional
      AppVersion: '1.0'
      agent: 'l17931-5'
  condition: always()
  
- stage: cf_push_deploy_1
  jobs:
  - template: ../cloudfoundry-deploy/cloudfoundry-deploy.yml
    parameters:
      additionalDeployArgs: '--version'
      artifactName: 'drop'
      buildType: 'specific'
      buildVersion: 'latest' # Default 'latest'. Specifies what build version to download e.g. latest, specific, or latestFromBranch
      environment: 'staging'
      ManifestPath: '/drop/manifests/manifest-test.yml' # Optional. Default to drop folder.
      #org: 'ESM'
      pipeline: '4360'
      pool: 'Private Linux'
      ArtifactProject: '$(System.TeamProject)'    # https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
      runUnzipTask: false
      space: 'alm-test'
      specificBuildWithTriggering: true
      targetPath: '$(Pipeline.Workspace)' # Directory to download the artifact files to.
      ZipFilePattern: '**/*.zip'
      checkout: CodeRepository
  condition: always()

- stage: Artifactory_Java_Build_1
  jobs:
  - template: ../templates/azure-java-mvn.yml
    parameters:
      AppName: 'Java-Mikes'
      Portfolio: 'ESM'
      RunMavenSonarScan: 'true'
      MavenGoal: 'clean install' # Optional
      targetResolveReleaseRepo: 'mvn' # Optional
      targetResolveSnapshotRepo: 'mvn'# Optional
      targetDeployReleaseRepo: 'mvn-local-ics-releases'# Optional
      targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'# Optional
      continueOnError: false  # 'true' if future steps should run even if this step fails; defaults to 'false'
      checkout: CodeRepository
  condition: always()

- stage: Artifactory_upload_one
  jobs:
  - template: ../azure-java-mvn-docker/azure-java-mvn-docker.yml
    parameters:
      AppName: 'Docker-Mikes'
      Portfolio: 'ESM'
      RunMavenSonarScan: 'true'
      ArtifactoryExtDockerRegistry: 'ALM Docker'
      MavenGoal: 'clean install' # Optional
      continueOnError: false  # 'true' if future steps should run even if this step fails; defaults to 'false'
      GenericUpload: 'false'
      checkout: CodeRepository
  condition: always()