trigger: none
pr: none

resources:
  repositories:
    - repository: Azure
      type: git
      name: xxx/xxxxxxxxxxxxxxx

variables:
  - group: 'Azure account provisioning Full variable list'
  - name: AZURE_TENANT
    value: ""

stages:
  - stage: createazuresubscription
    displayName: Create Azure Subscription
    variables:
    - template: /variables/${{ variables.AZURE_TENANT }}.yml

    jobs:
      - template: templates/validate-inputs.yml
        parameters:
          AgentPool: $(POOL)
          CloudRegionParam: $(CLOUD_PROVIDER_REGION)
          JobName: "ValidateInputs"
          IsBeta: ${{ variables.isBeta}}
          AzureGroupSyncService: ${{ variables.azureGroupSyncService }}
          StorageAccountName: $(STORAGE_NAME)
          ReadySubscriptionName: $(SUBSCRIPTION_NAME)
          UserProvided: $(USER_PROVIDED)
          SigninEmail: $(EMAIL)
          Lane: $(LANE)
          UseNonProdKeyVault: $(USE_NON_PROD_KEY_VAULT)
          DestinationTenant: $(AZURE_TENANT)
          ServiceConnectionName: ${{ variables.SERVICE_CONNECTION }}

      - template: templates/get-variables-from-key-vault.yml
        parameters:
          AgentPool: $(POOL)
          JobName: "AzureKeyVault"
          ServiceConnectionName: $(KEY_VAULT_SERVICE_CONNECTION)
          UseNonProdKeyVault: $(USE_NON_PROD_KEY_VAULT)
          DestinationTenant: $(AZURE_TENANT)
          DependsOn:
            - ValidateInputs 

      - template: templates/request-jwt.yml
        parameters:
          AgentPool: $(POOL)
          JobName: "RequestJwt"
          DependsOn:
            - AzureKeyVault

      - template: templates/get-customer.yml
        parameters:
          JobName: "CustomerVariables"
          DependsOn:
            - AzureKeyVault
            - RequestJwt

      - template: templates/send.yml
        parameters:
          JobName: SendEvent1
          DisplayName: "(STATUS Setting Subscription ID)"
          EventsId: $[ dependencies.CustomerVariables.outputs['OUTPUT.EVENT'] ]
          Message: "SUBSCRIPTION_ID!!$(SUBSCRIPTION_ID)" 
          DependsOn:
            - RequestJwt
            - AzureKeyVault

      - template: templates/base.yml
        parameters:
          AgentPool: $(POOL)
          JobName: "base"
          DependsOn:
            - AzureKeyVault

#       - template: templates/apply-subscription-tags.yml
#         parameters:
#           AgentPool: $(POOL)
#           ServiceConnectionName: ${{ variables.SERVICE_CONNECTION }}
#           SubscriptionId: $(SUBSCRIPTION_ID)
#           SubscriptionOwnerGroup: $(SERVICE_NOW_OWNER_GROUP)
#           SubscriptionOwningPortfolio: $(PORTFOLIO)
#           SubscriptionSolution: $(SOLUTION)
#           SubscriptionEnvironment: $(ENVIRONMENT)
#           JobName: ApplySubscriptionTags
#           DependsOn:
#             - ValidateInputs
#             - AzureKeyVault

#       - template: templates/divvy.yml
#         parameters:
#           JobName: "DSst"
#           TENANT_ID: $(TENANT_ID)
#           Portfolio: $(PORTFOLIO)
#           Solution: $(SOLUTION)
#           Environment: $(ENVIRONMENT)
#           DependsOn:
#             - AzureKeyVault
