###################################
# This creates a repository resource
# named ALMTemplates and points to
# the ALM devops_pipeline repository.
###################################
resources:
  repositories:                                                                             
    - repository: 'AlmTemplates'
      type: git
      name: ALM/devops_pipelines
    
trigger:
- none                                                                                       # Change this value to a branch name if a CI build is desired. For more information on triggers: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#ci-triggers
    
stages:
  - stage: 'Build Stage'                                                                     # Name the stage what ever you like. For more information on stages: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/stages?view=azure-devops&tabs=yaml
    jobs:
      - job:
        displayName: Build                                                                   # Again name the job what ever you want. For more information on jobs: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=azure-devops
        pool:
          name: Default                                                                      # Change the pool name to which ever pool is needed. Use 'Default' for Windows agents 'Private Linux' for Linux agents.
        steps:                                                                               # More Documenatation on steps docs: https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#steps
        - template: download-build-artifact/download-build-artifact.yml@AlmTemplates         # This line calls the ALM .Net Core template task. If any default parameters need to be changed, uncomment the parameter section and the parameter that needs to be changed.steps:
 
          parameters:
            # Optional buildType: current                                                               # valid values are "current" if the artifact is created in current pipeline or "specific" if created in another pipeline.
            project: ""                                                                      # set if using specific buildType. Project where the pipeline resides.
            pipeline: ""                                                                     # set if using specific buildType. Pipeline ID. Can get the ID from the pipeline URL.
            # Optional buildVersion: "latest"                                                           # set if using specific buildType. Valid values are "latest", "latestFromBranch", or "specific". The Pipeline run of the pipeline that generats the build artifact. 
            # Optional branchName: "master"                                                             # set if using specific buildType and BuildVersion is "latest", or "latestFromBranch". Specify to filter on branch/ref name, for example: refs/heads/develop.
            tag: ""                                                                          # set if using specific buildType and buildVersion is "latest", or "latestFromBranch". A comma-delimited list of tags. Only builds with these tags will be returned.
            buildID: ""                                                                      # set if using specific buildType and buildVersion is specific. The build run ID to download the artifact. The pipeline ID is in the URL of the pipeline run.
            # Optional downloadPath: "$(Build.ArtifactStagingDirectory)"                                # Path to download the artifact to.
            # Optional artifactName: "drop"                                                             # The name of the artifact to download.
            # Optional pattern: "drop/**"                                                               # Specify files to be downloaded as multi line minimatch pattern.
            # Optional downloadType: 'specific'                                                         # Download a specific artifact "single" or specific files "specific" from the build.