##############################################################
# Repo: devops_pipelines/templates
# File: azure-pipelines.yml
##############################################################
 
resources:
  repositories:
    - repository: templates
      type: git
      name: ALM/devops_pipelines
      ref: refs/tags/azure-java-mvn-docker2.x.x                                                     #tag reference for a specific version of the template we want to use.
  
stages:
- stage: Build
  jobs:
  - template: azure-java-mvn-docker/azure-java-mvn-docker.yml@templates
    parameters:
      Portfolio: 'portfolio name'                                                                   #Required    
      # Optional AppName: '$(Build.DefinitionName)'                                                 #This should be your application name
      # Optional ArtifactoryExtDockerRegistry: 'ALM Docker'                                         #Default value "ALM Docker"
      # Optional ArtifactoryServiceConnection: 'ALM Artifactory Internal'                           #Default value "ALM Artifactory Internal"
      # Optional checkout: 'self'                                                                   #for more information please see https://confluence.churchofjesuschrist.org/display/ALM/Pipeline+checkout+feature
      # Optional Dockerfile: '**/Dockerfile'                                                        #Default Searches for the Dockerfile, and pulls the first one it finds
      # Optional DownloadSecureFile 'false'                                                         #Default false meaning we don't have a secure file to download   
      # Optional JdkVersionOption: '1.11'                                                           #Default is 1.11. Use 1.8 for JDK 8
      # Optional MavenGoal: "clean install"                                                         #Default runs a clean install
      # Optional MavenPomPath: '.'                                                                  #Default Location of Maven pom file. Modify the path for Java modules.
      # Optional RunArtifactoryUpload: 'true'                                                       #Default Do we need to upload to artifactory with this run?
      # Optional RunDependencyUpdate: 'false'                                                       #Default is false
      # Optional RunMavenSonarScan: 'true'                                                          #Default true
      # Optional SonarServiceConnection: 'ALM Sonar'                                                #Default value "ALM Sonar"
      # Optional targetDeployReleaseRepo: 'mvn-local-ics-releases'                                  #Default is set by the ALM Team on all projects. If you want to use a different targetDeployReleaseRepo, pass the name in here.
      # Optional targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'                                #Default is set by the ALM Team on all projects. If you want to use a different targetDeploySnapshotRepo, pass the name in here.
      # Optional targetResolveReleaseRepo: 'mvn'                                                    #Default is set by the ALM Team on all projects. If you want to use a different targetResolveReleaseRepo, pass the name in here.
      # Optional targetResolveSnapshotRepo: 'mvn'                                                   #Default is set by the ALM Team on all projects. If you want to use a different targetResolveSnapshotRepo, pass the name in here.
      # Optional ContentsVars:                                                                      #Default is three variables -
      #             Variable1: "**/*.jar"                                                           #                            Variable1: "**/*.jar"
      #             Variable2: "**/manifest*.yml"                                                   #                            Variable2: "**/manifest*.yml"
      #             Variable3: "pom.xml"                                                            #                            Variable3: "pom.xml"
