###############################################################################################################
# ALM Team Azure example pipeline that pulls in the maven build template from the devops_pipelines repository
# Copy this file to your repository and fill in the required parameters, AppName and Portfolio
# Commit the changes and trigger a new build
###############################################################################################################
trigger:
- master
 
#################################### 
# Repo: devops_pipelines/templates
# File: azure-pipelines.yml
#################################### 
resources:
  repositories:
    - repository: almtemplates
      type: git
      name: ALM/devops_pipelines
  
stages:
- stage: Build
  jobs:
  - template: templates/azure-java-mvn.yml@almtemplates
    parameters:
      Portfolio: 'your portfolio name'
      # Optional AppName: 'your app name'                                   #Default value $(Build.DefinitionName)
      # Optional ArtifactoryServiceConnection: 'ALM Artifactory Internal'   #Default internal Artifactory service connection created by the ALM Team
      # Optional checkout: 'self'                                           #for more information please see https://confluence.churchofjesuschrist.org/display/ALM/Pipeline+checkout+feature
      # Optional DownloadSecureFile: 'false'                                #Do we have a secure file to download?
      # Optional JavaVersion: '11'                                          #Default maven version is 11. Pass in '8' for JDK 8
      # Optional MavenGoal: 'clean install'                                 #Default "clean install"
      # Optional MavenPomPath: '.'                                          #Location of Maven pom file
      # Optional RunArtifactoryUpload: 'true'                               #Do we need to upload a build to artifactory?
      # Optional RunDependencyUpdate: 'false'                               #Should we run a dependency update for our code?
      # Optional RunMavenSonarScan: 'true'                                  #Default set to 'false' if the branch name is not master
      # Optional targetResolveReleaseRepo: 'mvn'                            #Default "mvn"
      # Optional targetResolveSnapshotRepo: 'mvn'                           #Default "mvn"
      # Optional targetDeployReleaseRepo: 'mvn-local-ics-releases'          #Default "mvn-local-ics-releases"
      # Optional targetDeploySnapshotRepo: 'mvn-local-ics-snapshots'        #Default "mvn-local-ics-snapshots"
      # Optional SonarServiceConnection: 'ALM Sonar'                        #Default ALM Sonar service connection created by the ALM Team
      